apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner-docker
  namespace: prj-gitlab-runner
data:
  config.toml: |
    concurrent = 4
    check_interval = 1

    [[runners]]
      name = "gitlab-docker-runner"
      url = "https://git.ecommchannels.com/ci"
      token = "ZLqucKB7AT8bDBBMGdji"
      executor = "docker"
      [runners.docker]
        tls_verify = false
        image = "python:3.5"
        privileged = true
        disable_cache = false
        volumes = ["/cache"]
